### ISSUE TITLE
how do we define the document

### ISSUE THREAD

**Issue by alialnaghmoush** [moh-abdullah-it/firestore_model#13]
When using SubCollection, how do we define the document in the Parent Collection?

**Comment by moh-abdullah-it** [comment]
Parent Model => User
```dart
class User extends FirestoreModel<User> {
}
```
Sub Model => Post
```dart
class Post extends SubCollectionModel<Post> {
}
```
inject all models:
```dart
FirestoreModel.injectAll([User(), Post()]);
```
you need to create post to this user:
1. must have parent user as a model.
```dart
User user = await FirestoreModel.use<User>().find('testDocId');
```
2. get subCollection for this user:
```dart 
Post post = user.subCollection<Post>();
//to create new post
post.title = 'test post title';
post = await post.create();

// get data from subCollection
List<Post> posts = await user.subCollection<Post>().get();

//or you can use builders
ModelStreamGetBuilder<Post>(
parentModel: user,
builder: (_, snapshot) {
// your list builder
}
);
 ```

**Comment by alialnaghmoush** [comment]
```
Client? client = await FirestoreModel.use<Client>().find('XBynD0oj1okN0Hht0jDX');

Category newCategory = client!.subCollection<Category>();
      newCategory.name = {'en': nameEn.text, 'ar': nameAr.text};
      newCategory.sku = 'CA-${sku.text}';
      newCategory.isActive = isActive.value;
      newCategory = (await newCategoryo.create())!;
```

Error:
VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?'
#0      new Client.formMap
package:nextorder/…/models/client.dart:9
#1      Client.responseBuilder.<anonymous closure>
package:nextorder/…/models/client.dart:15
#2      FirestoreModel._responseBuilder
package:firestore_model/src/firestore_model.dart:47
#3      FirestoreModel._initReference.<anonymous closure>
package:firestore_model/src/firestore_model.dart:54
#4      _WithConverterDocumentSnapshot.data
package:cloud_firestore/src/document_snapshot.dart:119
#5      FirestoreModel._toModel
package:firestore_model/src/firestore_model.dart:62
#6      FirestoreModel.find.<anonymous closure>
package:firestore_model/src/firestore_model.dart:105
#7      _rootRunUnary (dart:async/zone.dart:1436:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
#9      FirestoreModel.find (package:firestore_<…>


```
class Client extends FirestoreModel<Client> {
  String? name;

  Client({this.name});

  Client.formMap(Map<String, dynamic> map) : name = map['name'];

  @override
  Map<String, dynamic> get toMap => {'name': name};

  @override
  ResponseBuilder<Client> get responseBuilder => (map) => Client.formMap(map);

}
```

```
class Category extends SubCollectionModel<Category> {
  late Map? name;
  late int? index, color;
  late String? imagePath, sku;
  late bool? isActive;

  Category({
    this.name,
    this.imagePath,
    this.sku,
    this.color,
    this.index,
    this.isActive,
  });

  Category.fromMap(Map<String, dynamic> snapshot)
      : this(
          name: snapshot['name'],
          imagePath: snapshot['imagePath'],
          sku: snapshot['sku'],
          color: snapshot['color'],
          index: snapshot['index'],
          isActive: snapshot['isActive'],
        );

  Category.fromDoc(DocumentSnapshot snapshot)
      : this(
          name: snapshot['name'],
          imagePath: snapshot['imagePath'],
          sku: snapshot['sku'],
          color: snapshot['color'],
          index: snapshot['index'],
          isActive: snapshot['isActive'],
        );

  @override
  Map<String, dynamic> get toMap => {
        'name': name,
        'imagePath': imagePath,
        'sku': sku,
        'color': color,
        'index': index,
        'isActive': isActive,
      };

  @override
  ResponseBuilder<Category> get responseBuilder =>
      (map) => Category.fromMap(map);
}

```

**Comment by alialnaghmoush** [comment]
```dart
Client client = FirestoreModel.use<Client>();
      Category? newCategory = client.subCollection<Category>();

      newCategory.name = {'en': nameEn.text, 'ar': nameAr.text};
      newCategory.sku = 'CA-${sku.text}';
      newCategory.isActive = isActive.value;
      newCategory = await newCategory.create(docId: 'XBynD0oj1okN0Hht0jDX');
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:cloud_firestore/src/firestore.dart': Failed assertion: line 67 pos 7: 'isValidCollectionPath(collectionPath)': a collection path must point to a valid collection.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      FirebaseFirestore.collection
package:cloud_firestore/src/firestore.dart:67
#3      FirestoreModel._initReference
package:firestore_model/src/firestore_model.dart:52
#4      FirestoreModel._collectionReference
package:firestore_model/src/firestore_model.dart:14
#5      FirestoreModel.create
package:firestore_model/src/firestore_model.dart:96
#6      CategoryController.addNewCategory
package:nextorder/…/category/categoryController.dart:122
#7      CategoryController.setAppBarForAdding.<anonymous closure>
package:nextorder/…/category/categoryController.dart:57
#8      _InkResponseSt<…>

**Comment by moh-abdullah-it** [comment]
> ```dart
> Client client = FirestoreModel.use<Client>();
>       Category? newCategory = client.subCollection<Category>();
> 
>       newCategory.name = {'en': nameEn.text, 'ar': nameAr.text};
>       newCategory.sku = 'CA-${sku.text}';
>       newCategory.isActive = isActive.value;
>       newCategory = await newCategory.create();
> ```
> 
> [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:cloud_firestore/src/firestore.dart': Failed assertion: line 67 pos 7: 'isValidCollectionPath(collectionPath)': a collection path must point to a valid collection.
> #0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> #1 _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> #2 FirebaseFirestore.collection
> package:cloud_firestore/src/firestore.dart:67
> #3 FirestoreModel._initReference
> package:firestore_model/src/firestore_model.dart:52
> #4 FirestoreModel._collectionReference
> package:firestore_model/src/firestore_model.dart:14
> #5 FirestoreModel.create
> package:firestore_model/src/firestore_model.dart:96
> #6 CategoryController.addNewCategory
> package:nextorder/…/category/categoryController.dart:122
> #7 CategoryController.setAppBarForAdding.
> package:nextorder/…/category/categoryController.dart:57
> #8 _InkResponseSt<…>

that is not document: 
```dart
Client client = FirestoreModel.use<Client>(); /// this only instance form your model
```
to work with sub collection you need to have parent document as a model like this:
```dart
Client? client = await FirestoreModel.use<Client>().find('XBynD0oj1okN0Hht0jDX');
//and this is your subCollection
//path: clients/XBynD0oj1okN0Hht0jDX/categories
Category newCategory = client!.subCollection<Category>(); 
```

**Comment by moh-abdullah-it** [comment]
> ```dart
> Client? client = await FirestoreModel.use<Client>().find('XBynD0oj1okN0Hht0jDX');
> 
> Category newCategory = client!.subCollection<Category>();
>       newCategory.name = {'en': nameEn.text, 'ar': nameAr.text};
>       newCategory.sku = 'CA-${sku.text}';
>       newCategory.isActive = isActive.value;
>       newCategory = (await newCategoryo.create())!;
> ```
> 
> Error:
> VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?'
> #0 new Client.formMap
> package:nextorder/…/models/client.dart:9
> #1 Client.responseBuilder.
> package:nextorder/…/models/client.dart:15
> #2 FirestoreModel._responseBuilder
> package:firestore_model/src/firestore_model.dart:47
> #3 FirestoreModel._initReference.
> package:firestore_model/src/firestore_model.dart:54
> #4 _WithConverterDocumentSnapshot.data
> package:cloud_firestore/src/document_snapshot.dart:119
> #5 FirestoreModel._toModel
> package:firestore_model/src/firestore_model.dart:62
> #6 FirestoreModel.find.
> package:firestore_model/src/firestore_model.dart:105
> #7 _rootRunUnary (dart:async/zone.dart:1436:47)
> #8 _CustomZone.runUnary (dart:async/zone.dart:1335:19) #9 FirestoreModel.find (package:firestore_<…>
> 
> ```dart
> class Client extends FirestoreModel<Client> {
>   String? name;
> 
>   Client({this.name});
> 
>   Client.formMap(Map<String, dynamic> map) : name = map['name'];
> 
>   @override
>   Map<String, dynamic> get toMap => {'name': name};
> 
>   @override
>   ResponseBuilder<Client> get responseBuilder => (map) => Client.formMap(map);
> 
> }
> ```
> 
> ```dart
> class Category extends SubCollectionModel<Category> {
>   late Map? name;
>   late int? index, color;
>   late String? imagePath, sku;
>   late bool? isActive;
> 
>   Category({
>     this.name,
>     this.imagePath,
>     this.sku,
>     this.color,
>     this.index,
>     this.isActive,
>   });
> 
>   Category.fromMap(Map<String, dynamic> snapshot)
>       : this(
>           name: snapshot['name'],
>           imagePath: snapshot['imagePath'],
>           sku: snapshot['sku'],
>           color: snapshot['color'],
>           index: snapshot['index'],
>           isActive: snapshot['isActive'],
>         );
> 
>   Category.fromDoc(DocumentSnapshot snapshot)
>       : this(
>           name: snapshot['name'],
>           imagePath: snapshot['imagePath'],
>           sku: snapshot['sku'],
>           color: snapshot['color'],
>           index: snapshot['index'],
>           isActive: snapshot['isActive'],
>         );
> 
>   @override
>   Map<String, dynamic> get toMap => {
>         'name': name,
>         'imagePath': imagePath,
>         'sku': sku,
>         'color': color,
>         'index': index,
>         'isActive': isActive,
>       };
> 
>   @override
>   ResponseBuilder<Category> get responseBuilder =>
>       (map) => Category.fromMap(map);
> }
> ```

please check `name` value in document
